spring.application.name=shogiv2

spring.jpa.hibernate.ddl-auto=update

# PostgreSQLの設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shogiv2
spring.datasource.username=souma1024
spring.datasource.password=shogiv2